#!/bin/bash

set -x

APP_DIR=$PWD

# exit if the bootstrap.ran file exists
if [ -f "$APP_DIR/bootstrap.ran" ]; then
  echo "Bootstrap already ran. Exiting."
  exit 0
fi

# add a call to lfg every N minute(s)
(crontab -l 2>/dev/null | grep -v 'lfg' ; echo "*/10 * * * * $APP_DIR/lfg >> $APP_DIR/lfg.log 2>&1") | crontab -

touch "$APP_DIR/bootstrap.ran"