#!/bin/bash

set -x

SOURCE_IMAGE=$1

# an attempt at stopping directory traversal
if [[ "$SOURCE_IMAGE" == *..* || "$SOURCE_IMAGE" == ^/* || "$SOURCE_IMAGE" == *\\* ]]
then
  echo "Error: Unsafe directory traversal input detected."
  exit 1
fi

APP_DIR=$PWD
SOURCE_IMAGE_FILENAME=$APP_DIR/$SOURCE_IMAGE
COLOR_CONVERTER_SCRIPT=$APP_DIR/image-converter/color_epd_converter.py
COLOR_CONVERTER_EXPORT=$APP_DIR/converted/ben_is_a_hack.bmp
E_INK_PIC_DIR=$APP_DIR/e-paper/source
E_INK_SCRIPT=$APP_DIR/e-paper/examples/mma-e-paper.py

# do we have an expected file type?
FILETYPE=$(file --mime-type -b "$SOURCE_IMAGE_FILENAME")
case "$FILETYPE" in
  image/jpeg|image/png|image/gif|image/bmp)
    echo "Valid image file"
    ;;
  *)
    echo "Invalid file type"
    exit 2
    ;;
esac

# for now, we're cleaning house with each execution
rm -f $COLOR_CONVERTER_EXPORT $E_INK_PIC_DIR/ben_is_a_hack.bmp

# convert baby!
python3 $COLOR_CONVERTER_SCRIPT $SOURCE_IMAGE_FILENAME

cp $COLOR_CONVERTER_EXPORT $E_INK_PIC_DIR/ben_is_a_hack.bmp

cd e-paper

# update screen
python3 $E_INK_SCRIPT
